---
title: 'First Year Exam: Question 15'
author: "Rachel Weinstein (A11836450)"
date: "7/8/2022"
output: github_document
---

```{r}
# Load necessary packages

library(dplyr)
library(lubridate)
library(ggplot2)
```

```{r}
# Import the data

data <- read.csv("covid19_variants.csv")
```

```{r}
# Filter out 'Other' and 'Total' from variants

clean_data <- filter(data, variant_name != "Other", variant_name != "Total")
```

```{r}
# Change name of column "variant_name" to "Variant" (an aesthetic change for the final figure)

clean_data <- rename(clean_data, Variant = variant_name)
```

```{r}
# Make data lubridate compatible

clean_data$date <- ymd(clean_data$date)
```

```{r}
# Plot the data

ggplot(clean_data, aes(date, percentage, color = Variant))+
  geom_line()+
  scale_x_date(date_breaks = "1 month", date_labels =  "%b %Y")+
  theme(axis.text.x=element_text(angle=60, hjust=1))+
  labs(x = "", y = "Percent of sequenced specimens", title = "Covid-19 Variants in California", caption = "Data Source: <https://www.cdph.ca.gov/>")
```
